### ISSUE TITLE
PHP Warning:  require_once(/var/www/html/Arb/ccxt/php/BaseError.php): failed to open stream: No such file or directory in /var/www/html/Arb/ccxt/ccxt.php on line 59

### ISSUE THREAD

**Issue by berkse** [federosso/Arb_Trng_BIN_Console#1]
PHP Warning:  require_once(/var/www/html/Arb/ccxt/php/BaseError.php): failed to open stream: No such file or directory in /var/www/html/Arb/ccxt/ccxt.php on line 59

I see this error. I think BaseError page is missing

**Comment by federosso** [comment]
Hi thank you very much for reporting.
The base folder (/ ccxt / php / base /) with the related files was missing.
Now it is OK

![error](https://user-images.githubusercontent.com/1715937/137224961-2a60a97c-71ab-4ee9-9ddf-6d0bc0e8a140.png)
